apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure scraping (generic dev infra stack)
  - servicemonitor-rabbitmq.yaml
  - mongodb-exporter-deployment.yaml
  - podmonitor-mongodb.yaml
